Fu a defragment - fixes issue #427
jcodec/jcodec pull request #428
Opened 2020-07-20 09:54 UTC by vidtec

Resolves Issue #427 

Also adds some unit tests for NAL related items, and fully tested NAL reassembly.
Also introduces test coverage tool into build

2020-09-14 13:54 UTC, zhuker requested changes
nice work!

please update formatting on unit tests, otherwise great!

2020-09-14 13:54 UTC, zhuker commented on src/test/java/org/jcodec/codecs/h264/io/model/NALReassembleTest.java
> +		byte[][] data = new byte[][]
please use 4 spaces indent

2020-09-14 13:54 UTC, zhuker commented on src/test/java/org/jcodec/codecs/h264/io/model/NalUnitTest.java
> +    	byte[] data = new byte[] { (byte)0x7C, (byte)0x81  };
please use 4 spaces indentation

2020-09-15 09:15 UTC, gareth-floodgate commented
Whitespace formatting issues corrected in commit dd1fe9f - please go ahead and finalise for merge

Thanks

2020-09-15 14:06 UTC, zhuker commented on src/test/java/org/jcodec/codecs/h264/io/model/NalUnitTest.java
> +    	byte[] data = new byte[] { (byte)0x7C, (byte)0x81  };
> Whitespace formatting issues corrected in commit [dd1fe9f](https://github.com/jcodec/jcodec/commit/dd1fe9fdad5346ee10f20114a331271efaaa2987) - please go ahead and finalise for merge
> 
> Thanks

NalUnitTest.java still uses 2 spaces @gareth-floodgate

2020-09-15 17:36 UTC, gareth-floodgate commented
Apologies - updated this file in commit c6adfa3

2020-09-15 22:15 UTC, zhuker approved these changes

2020-09-15 22:15 UTC, merged